Models/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using SOFT703.Models.ViewModels.Contracts;
using SOFT703.Services;
using SOFT703.Services.Contracts;

namespace SOFT703.Models.ViewModels;

public class LoginViewModel : ILoginViewModel
{
    [Required(ErrorMessage = "Please enter your email.")]
    [EmailAddress(ErrorMessage = "Invalid email format. Please enter a valid email.")]
    public string Email { get; set; }

    [Required(ErrorMessage = "Password is required.")]
    [DataType(DataType.Password)]
    public string? Password { get; set; }

    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? PhoneNumber { get; set; }


    private readonly IUserService _userService;


    public LoginViewModel(IUserService userService)
    {
        _userService = userService;
   
    }

    public LoginViewModel()
    {
    }

    public async Task<bool> Login()
    {
        return await _userService.Login(this.Email, this.Password);
    }

    public async Task LogOut()
    {
        await _userService.LogOut();
    }

    public async Task<bool> SignIn()
    {
        var user = new User()
        {
            Email = this.Email,
            UserName = this.Email,
            FirstName = this.FirstName,
            LastName = this.LastName,
            PhoneNumber = this.PhoneNumber,
            EmailConfirmed = true
            
        };
        return await _userService.SignIn(user, this.Password);

    }

    public async Task AddUser(string role)
    {
        var user = new User()
        {
            Email = this.Email,
            UserName = this.Email,
            FirstName = this.FirstName,
            LastName = this.LastName,
            PhoneNumber = this.PhoneNumber,
            EmailConfirmed = true
            
        };
        await _userService.AddDefaultAsync(user, this.Password);
        await _userService.SetRole(user.Email, "staff");
    }


    public Task DeleteAsync(string id)
    {
        throw new NotImplementedException();
    }

    public Task GetByIdAsync(string id)
    {
        throw new NotImplementedException();
    }

    public Task GetAllAsync()
    {
        throw new NotImplementedException();
    }

    public Task<User> AddAsync(User entity)
    {
        throw new NotImplementedException();
    }

    public Task<User> UpdateAsync(string id, User newEntity)
    {
        throw new NotImplementedException();
    }
}

Models/ViewModels/UserDetailViewModel.cs
using SOFT703.Models.ViewModels.Contracts;
using SOFT703.Services.Contracts;

namespace SOFT703.Models.ViewModels;

public class UserDetailViewModel : IUserDetailViewModel
{
    public User? User { get; set; }
    public List<Transaction> Transactions { get; set; }
    public List<Trolley> Trolleys { get; set; }

    private readonly IUserService _userService;

    public UserDetailViewModel(IUserService userService)
    {
        _userService = userService;
    }
    public UserDetailViewModel(){}

    public Task DeleteAsync(string id)
    {
        throw new NotImplementedException();
    }

    public Task GetByIdAsync(string id)
    {
        throw new NotImplementedException();
    }

    public Task GetAllAsync()
    {
        throw new NotImplementedException();
    }

    public Task<User> AddAsync(User entity)
    {
        throw new NotImplementedException();
    }

    public Task<User> UpdateAsync(string id, User newEntity)
    {
        throw new NotImplementedException();
    }

    public async Task Detail(string? Id)
    {
        this.User = await _userService.GetUserTrolleyTransaction(Id);
        this.Trolleys = User.Trolleys;
        this.Transactions = User.Transactions;
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SOFT703.Data;
using SOFT703.Models;
using SOFT703.Models.ViewModels;
using SOFT703.Models.ViewModels.Contracts;
using SOFT703.Services.Contracts;

namespace SOFT703.Controllers;

public class LoginController : Controller
{
    //Cambiar el nombre de tus variables igual
    private readonly ILoginViewModel _loginVM;
    private readonly IUserDetailViewModel  _userDetailViewModel;

    public LoginController( ILoginViewModel vm, IUserDetailViewModel userDetailViewModel)
    {
        _loginVM = vm;
        _userDetailViewModel = userDetailViewModel;
    }

    [HttpGet]
    [AllowAnonymous]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Login(LoginViewModel model)
    {
        if (ModelState.IsValid)
        {
            _loginVM.Email = model.Email;
            _loginVM.Password = model.Password;
            if (await _loginVM.Login())
            {
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError(string.Empty, "Invalid email or password. Please try again.");
        }

        return View(model);
    }

    public IActionResult SignIn()
    {
        return View("SignIn");
    }

    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SignIn(LoginViewModel model)
    {

        //Podes invertir tu condicion para no tener muchos if anidados. Es buena practica evitar eso
        
        if(!ModelState.IsValid) return View("SignIn", model);
        
        _loginVM.Password = model.Password;
        _loginVM.Email = model.Email;
        _loginVM.FirstName = model.FirstName;
        _loginVM.LastName = model.LastName;
        _loginVM.PhoneNumber = model.PhoneNumber;

        if (await _loginVM.SignIn()) return RedirectToAction("Index", "Home");
        
        ModelState.AddModelError(string.Empty, "Invalid email or password. Please try again.");
        
        return View("SignIn", model);
    }

    public async Task<IActionResult> LogOut()
    {
        await _loginVM.LogOut(); 
        return RedirectToAction("Index", "Home");
    }


    public async Task<IActionResult> UserDetail(string userId)
    {
        await _userDetailViewModel.Detail(null);
        return View("UserDetail", _userDetailViewModel);
    }
}

Controllers/TrolleyController.cs
using Microsoft.AspNetCore.Mvc;
using SOFT703.Models.ViewModels.Contracts;

namespace SOFT703.Controllers;

public class TrolleyController : Controller
{
    private readonly ITrolleyViewModel _trolleyViewModel;
    public TrolleyController(ITrolleyViewModel trolleyViewModel)
    {
        _trolleyViewModel = trolleyViewModel;
    }

    public async Task<ViewResult> Detail(string id)
    {
        await _trolleyViewModel.GetByIdAsync(id);
        return View(_trolleyViewModel);
    }
}

Views/Login/Login.cshtml
@model SOFT703.Models.ViewModels.Contracts.ILoginViewModel

@{
    ViewData["Title"] = "Login Page";
}

<h2>Login</h2>

<form asp-controller="Login" asp-action="Login" method="post">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label asp-for="Email">Email</label>
        <input asp-for="Email" class="form-control"/>
        <span asp-validation-for="Email" class="text-danger"></span>
 
    </div>
    <div class="form-group">
        <label asp-for="Password">Password</label>
        <input asp-for="Password" type="password" class="form-control"/>
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

</form>

Views/Login/SignIn.cshtml
@model SOFT703.Models.ViewModels.LoginViewModel

<form asp-controller="Login" asp-action="SignIn" method="post">
    <div class="form-group">
        <label asp-for="Email">Email</label>
        <input asp-for="Email" class="form-control"/>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Password">Password</label>
        <input asp-for="Password" type="password" class="form-control"/>
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FirstName">FirstName</label>
        <input asp-for="FirstName" class="form-control"/>

    </div>
    <div class="form-group">
        <label asp-for="LastName">LastName</label>
        <input asp-for="LastName" class="form-control"/>

    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber">PhoneNumber</label>
        <input asp-for="PhoneNumber" class="form-control"/>

    </div>


    <button type="submit" class="btn btn-primary">Sign In</button>
</form>

Views/Login/UserDetail.cshtml
@model SOFT703.Models.ViewModels.Contracts.IUserDetailViewModel

@{
    ViewBag.Title = "User Detail";
    Layout = "_Layout"; // Set your layout page here
}
<h2>User Information</h2>
<div>
    <p>
        <strong>Username:</strong> @Model.User.UserName
    </p>
    <p>
        <strong>Email:</strong> @Model.User.Email
    </p>
    <p>
        <strong>Phone:</strong> @Model.User.PhoneNumber
    </p>
    <p>
        <strong>First Name:</strong> @Model.User.FirstName
    </p>
    <p>
        <strong>Last Name:</strong> @Model.User.LastName
    </p>
</div>

<h2>Money Sent</h2>
<table class="table">
    <thead>
    <tr>
        <th>Amount</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Amount Converted</th>
        <th>Date</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var transaction in Model.Transactions)
    {
        <tr>
            <td>@transaction.Amount</td>
            <td>@transaction.Exchange.SenderCountry.Name</td>
            <td>@transaction.Exchange.ReceiverCountry.Name</td>
            <td>@transaction.AmountConverted</td>
            <td>@transaction.TransactionDate</td>
        </tr>
    }
    </tbody>
</table>

<h2>Handicraft Purchases</h2>
<table class="table">
    <thead>
    <tr>
        <th>Date</th>
        <th>Total</th>

    </tr>
    </thead>
    <tbody>
    @foreach (var trolley in Model.Trolleys)
    {
        @if (!trolley.IsCurrent)
        {
            <tr>
                <td>@trolley.TransactionDate</td>
                <td>@trolley.Total</td>
                <td>
                    <a href="@Url.Action("Detail", "Trolley", new { id = trolley.Id })" class="btn btn-primary">Detail</a>
                </td>
            </tr>
        }
    }
    </tbody>
</table>