Models/ViewModels/ManagementProductViewModel.cs
using SOFT703.Models.ViewModels.Contracts;
using SOFT703.Services;
using SOFT703.Services.Contracts;

namespace SOFT703.Models.ViewModels;

public class ManagementProductViewModel: IManagementProductViewModel
{
    private readonly IProductService _productService;
    public List<Product>? Products { get; set; }
    public Product? Product { get; set; }

    public ManagementProductViewModel(IProductService productService)
    {
        _productService = productService;
    }

    public ManagementProductViewModel()
    {
    }

    public async Task DeleteAsync(string id)
    {
        await  _productService.DeleteAsync(id);
    }

    public async Task GetByIdAsync(string id)
    {
        this.Product = await _productService.GetByIdAsync(id);
    }

    public async Task GetAllAsync()
    {
        this.Products = await _productService.GetAllAsync();
    }

    public Task<Product> AddAsync(Product entity)
    {
        return _productService.AddAsync(entity);
    }

    public async Task<Product> UpdateAsync(string id, Product newEntity)
    {
        var entity = await _productService.GetByIdAsync(id);
        entity.Name = newEntity.Name;
        entity.Price = newEntity.Price;
        entity.Photo = newEntity.Photo;
        entity.Stock = newEntity.Stock;
        return await _productService.UpdateAsync(entity);
    }
}

Controllers/ManagementProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SOFT703.Data;
using SOFT703.Models.ViewModels;
using SOFT703.Models.ViewModels.Contracts;

namespace SOFT703.Controllers;


//Por mas que no sea una api, los endpoints deberían ser sustantivos en plural
public class ManagementProductController : Controller
{
    private readonly IManagementProductViewModel _vm;

    public ManagementProductController(IManagementProductViewModel vm)
    {
        _vm = vm;
    }

    // GET
    public async Task<IActionResult> Index()
    {
        await _vm.GetAllAsync();
        return View(_vm);
    }


    //Lo mismo evitemos los if anidados, como este metodo es un update tu metodo deberia ser un put o patch
    // usualemente cuando actualizas algo le mandas el id por la ruta y los datos a actualizar por el body, post no se usa para actualizar
    //el metodo puede ser asi

    [HttpPut("products/{id}")]
    public async Task<IActionResult> Edit(int id, [FromBody] object product)
    {
        //Y aqui hacer la magia


    }
    
    [HttpPost]
    [Authorize]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(string id, ManagementProductViewModel vm)
    {
        //Podes utilizar un if simplificado
        if (id != vm.Product.Id)    return NotFound(); 
        

        if (!ModelState.IsValid)
        {
           return View(vm);
        }

        try
        {
            await _vm.UpdateAsync(id, vm.Product);
            return RedirectToAction("Index");
        }
        //Para mas adelante es bueno controlar el tipo de excepciones de manera especifica
        catch (DbUpdateConcurrencyException)
        {
            ModelState.AddModelError(string.Empty, "Concurrency error occurred.");
        }

        return View(vm);
    }

    public async Task<IActionResult> Edit(string id)
    {
        await _vm.GetByIdAsync(id);
        return View(_vm);
    }

    public IActionResult Add()
    {
        return View(_vm);
    }

    [HttpPost]
    [Authorize]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Add(ManagementProductViewModel vm)
    {
        await _vm.AddAsync(vm.Product);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(string id)
    {
        await _vm.DeleteAsync(id);
        return RedirectToAction("Index");
    }
}

Views/ManagementProduct/Add.cshtml
@model SOFT703.Models.ViewModels.Contracts.IManagementProductViewModel


@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<form asp-controller="ManagementProduct" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Product.Name">Name</label>
        <input asp-for="Product.Name" class="form-control"/>
        <span asp-validation-for="Product.Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Product.Photo">Photo Url</label>
        <input asp-for="Product.Photo"  class="form-control"/>
        <span asp-validation-for="Product.Photo" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Product.Price">Price</label>
        <input asp-for="Product.Price" class="form-control"/>

    </div>
    <div class="form-group">
        <label asp-for="Product.Stock">Stock</label>
        <input asp-for="Product.Stock" class="form-control"/>

    </div>



    <button type="submit" class="btn btn-primary">Add</button>
</form>

Views/ManagementProduct/Edit.cshtml
@model SOFT703.Models.ViewModels.Contracts.IManagementProductViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<form asp-controller="ManagementProduct" asp-action="Edit" method="post">
    <input type="hidden" asp-for="Product.Id" />
    <div class="form-group">
        <label asp-for="Product.Name">Name</label>
        <input asp-for="Product.Name" class="form-control"/>
        <span asp-validation-for="Product.Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Product.Photo">Photo Url</label>
        <input asp-for="Product.Photo" class="form-control"/>
        <span asp-validation-for="Product.Photo" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Product.Price">Price</label>
        <input asp-for="Product.Price" class="form-control"/>

    </div>
    <div class="form-group">
        <label asp-for="Product.Stock">Stock</label>
        <input asp-for="Product.Stock" class="form-control"/>

    </div>



    <button type="submit" class="btn btn-primary">Update</button>
</form>

Views/ManagementProduct/Index.cshtml
@model SOFT703.Models.ViewModels.Contracts.IManagementProductViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Products</h2>
<a href="@Url.Action("Add", "ManagementProduct")" class="btn btn-primary">Add</a>

<table class="table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Photo Url</th>
        <th>Stock</th>
        <th>Price</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var product in Model.Products)
    {
        <tr>
            <td>@product.Name</td>
            <td>
                @if (product.Photo.Length > 30)
                {
                    <span title="@product.Photo">@product.Photo.Substring(0, 30)...</span>
                }
                else
                {
                    @product.Photo
                }
            </td>
            <td>@product.Stock</td>
            <td>@product.Price</td>
            <td>
                <a href="@Url.Action("Edit", "ManagementProduct", new { id = product.Id })" class="btn btn-primary">Edit</a>
                <a href="@Url.Action("Delete", "ManagementProduct", new { id = product.Id })" class="btn btn-primary">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>