Models/ViewModels/ManagementUserViewModel.cs
using SOFT703.Models.ViewModels.Contracts;
using SOFT703.Services.Contracts;

namespace SOFT703.Models.ViewModels;

public class ManagementUserViewModel:IManagementUserViewModel
{
    public List<User>? Users { get; set; }
    public User? User { get; set; }
    
    private readonly IUserService _userService;
    public ManagementUserViewModel(IUserService userService)
    {
        _userService = userService;
    }
    public ManagementUserViewModel(){}
    
    
    public async Task DeleteAsync(string id)
    {
        await _userService.DeleteAsync(id);
    }

    public async Task GetByIdAsync(string id)
    {
        this.User = await _userService.GetByIdAsync(id);
    }

    public async Task GetAllAsync()
    {
        Users = await _userService.GetAllAsync();
        var selfUser = Users.FirstOrDefault(x => x.Id == _userService.GetUserId());
        Users.Remove(selfUser);        
    }

    public Task<User> AddAsync(User entity)
    {
        throw new NotImplementedException();
    }

    public async Task<User> UpdateAsync(string id, User newEntity)
    {
        var foundUser = _userService.GetByIdAsync(id);
        if (foundUser == null)
        {
            throw new Exception("User not found");
        }
        foundUser.Result.Email = newEntity.Email;
        foundUser.Result.FirstName = newEntity.FirstName;
        foundUser.Result.LastName = newEntity.LastName;
        foundUser.Result.PhoneNumber = newEntity.PhoneNumber;
        return await _userService.UpdateAsync(foundUser.Result);
    }
}

Controllers/ManagementUserController.cs
using System.Runtime.Intrinsics.X86;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SOFT703.Data;
using SOFT703.Models;
using SOFT703.Models.ViewModels;
using SOFT703.Models.ViewModels.Contracts;

namespace SOFT703.Controllers;

public class ManagementUserController : Controller
{
    private readonly IUserDetailViewModel _userDetailViewModel;
    private readonly IManagementUserViewModel _managementUserViewModel;
    private readonly ILoginViewModel _loginViewModel;

    public ManagementUserController(IUserDetailViewModel vm, IManagementUserViewModel managementUserViewModel,
        ILoginViewModel loginViewModel)
    {
        _managementUserViewModel = managementUserViewModel;
        _userDetailViewModel = vm;
        _loginViewModel = loginViewModel;
    }

    public async Task<IActionResult> Index()
    {
        await _managementUserViewModel.GetAllAsync();
        return View(_managementUserViewModel);
    }

    public async Task<IActionResult> Detail(string id)
    {
        await _userDetailViewModel.Detail(id);
        return View(_userDetailViewModel);
    }

    public async Task<IActionResult> Edit(string id)
    {
        await _managementUserViewModel.GetByIdAsync(id);
        return View(_managementUserViewModel);
    }


    [HttpPost]
    [Authorize]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(ManagementUserViewModel vm)
    {
        if (!User.IsInRole("staff"))
        {
            ModelState.AddModelError(string.Empty, "You are not authorized to perform this action");
            return View(vm);
        }


        _managementUserViewModel.User = new User()
        {
            Email = vm.User.Email,
            FirstName = vm.User.FirstName,
            LastName = vm.User.LastName,
            PhoneNumber = vm.User.PhoneNumber,
        };
        await _managementUserViewModel.UpdateAsync(vm.User.Id, _managementUserViewModel.User);
        return RedirectToAction("Index");
    }

    public IActionResult Add()
    {
        return View(_loginViewModel);
    }

    [HttpPost]
    [Authorize]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Add(LoginViewModel vm)
    {
        _loginViewModel.Email = vm.Email;
        _loginViewModel.FirstName = vm.FirstName;
        _loginViewModel.LastName = vm.LastName;
        _loginViewModel.PhoneNumber = vm.PhoneNumber;
        _loginViewModel.Password = "Password1!";
        await _loginViewModel.AddUser("client");
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(string id)
    {
        await _managementUserViewModel.DeleteAsync(id);

        return RedirectToAction("Index");
    }
}

Controllers/TrolleyController.cs
using Microsoft.AspNetCore.Mvc;
using SOFT703.Models.ViewModels.Contracts;

namespace SOFT703.Controllers;

public class TrolleyController : Controller
{
    private readonly ITrolleyViewModel _trolleyViewModel;
    public TrolleyController(ITrolleyViewModel trolleyViewModel)
    {
        _trolleyViewModel = trolleyViewModel;
    }

    public async Task<ViewResult> Detail(string id)
    {
        await _trolleyViewModel.GetByIdAsync(id);
        return View(_trolleyViewModel);
    }
}

Views/ManagementUser/Add.cshtml
@model SOFT703.Models.ViewModels.Contracts.ILoginViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<form asp-controller="ManagementUser" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Email">Email</label>
        <input asp-for="Email" class="form-control"/>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Password">Password</label>
        <input asp-for="Password" type="password" class="form-control"/>
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FirstName">FirstName</label>
        <input asp-for="FirstName" class="form-control"/>

    </div>
    <div class="form-group">
        <label asp-for="LastName">LastName</label>
        <input asp-for="LastName" class="form-control"/>

    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber">PhoneNumber</label>
        <input asp-for="PhoneNumber" class="form-control"/>

    </div>


    <button type="submit" class="btn btn-primary">Sign In</button>
</form>

Views/ManagementUser/Detail.cshtml
@model SOFT703.Models.ViewModels.Contracts.IUserDetailViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h1>User Detail</h1>

<h2>User Information</h2>
<div>
    <p>
        <strong>Username:</strong> @Model.User.UserName
    </p>
    <p>
        <strong>Email:</strong> @Model.User.Email
    </p>
    <p>
        <strong>Phone:</strong> @Model.User.PhoneNumber
    </p>
    <p>
        <strong>First Name:</strong> @Model.User.FirstName
    </p>
    <p>
        <strong>Last Name:</strong> @Model.User.LastName
    </p>
</div>

<h2>User Transactions</h2>
<table class="table">
    <thead>
    <tr>
        <th>Amount</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Amount Converted</th>
        <th>Date</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var transaction in Model.Transactions)
    {
        <tr>
            <td>@transaction.Amount</td>
            <td>@transaction.Exchange.SenderCountry.Name</td>
            <td>@transaction.Exchange.ReceiverCountry.Name</td>
            <td>@transaction.AmountConverted</td>
            <td>@transaction.TransactionDate</td>
        </tr>
    }
    </tbody>
</table>

<h2>User Trolleys</h2>
<table class="table">
    <thead>
    <tr>
        <th>Date</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var trolley in Model.Trolleys)
    {
        <tr>
            <td>@trolley.TransactionDate</td>
            <td>@trolley.Total</td>
            <td>
                <a href="@Url.Action("Detail", "Trolley", new { id = trolley.Id })" class="btn btn-primary">Detail</a>
            </td>
        </tr>
    }
    </tbody>
</table>

Views/ManagementUser/Edit.cshtml
@model SOFT703.Models.ViewModels.Contracts.IManagementUserViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<form asp-controller="ManagementUser" asp-action="Edit" method="post">
    <input type="hidden" asp-for="User.Id" />
    <div class="form-group">
        <label asp-for="User.Email">Email</label>
        <input asp-for="User.Email" class="form-control"/>
    </div>

    <div class="form-group">
        <label asp-for="User.FirstName">FirstName</label>
        <input asp-for="User.FirstName" class="form-control"/>

    </div>
    <div class="form-group">
        <label asp-for="User.LastName">LastName</label>
        <input asp-for="User.LastName" class="form-control"/>

    </div>
    <div class="form-group">
        <label asp-for="User.PhoneNumber">PhoneNumber</label>
        <input asp-for="User.PhoneNumber" class="form-control"/>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>

Views/ManagementUser/Index.cshtml
@model SOFT703.Models.ViewModels.Contracts.IManagementUserViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Users</h2>
<a href="@Url.Action("Add", "ManagementUser")" class="btn btn-primary">Create User</a>
<table class="table">
    <thead>
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Phone</th>
        <th>First Name</th>
        <th>Last Name</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var users in Model.Users)
    {
        <tr>
            <td>@users.UserName</td>
            <td>@users.Email</td>
            <td>@users.PhoneNumber</td>
            <td>@users.FirstName</td>
            <td>@users.LastName</td>
            <td>
                <a href="@Url.Action("Detail", "ManagementUser", new { id = users.Id })" class="btn btn-primary">Details</a>
                <a href="@Url.Action("Edit", "ManagementUser", new { id = users.Id })" class="btn btn-primary">Edit</a>
                <a href="@Url.Action("Delete", "ManagementUser", new { id = users.Id })" class="btn btn-primary">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>